// This file is generated by npm run build:icons

export type IconName =
	| "lucide/external-link"
	| "lucide/eye"
	| "lucide/facebook"
	| "radix/accessibility"
	| "radix/activity-log"
	| "radix/archive"
	| "radix/arrow-bottom-left"
	| "radix/arrow-bottom-right"
	| "radix/arrow-down"
	| "radix/arrow-left"
	| "radix/arrow-right"
	| "radix/arrow-top-left"
	| "radix/arrow-top-right"
	| "radix/calendar"
	| "radix/camera"
	| "radix/envelope-closed"
	| "radix/envelope-open"
	| "radix/instagram-logo"
	| "radix/linkedin-logo"
	| "radix/mobile"
	| "sprite";
